vscode:
  extensions:
    - Cronos87.symfony-snippets@0.1.1:bAfj4oB7nfHeTAdrpdbBJw==
    - whatwedo.twig@1.0.2:yjUyDW+J4T2IZ2gBu830CQ==
    - TheNouillet.symfony-vscode@1.0.2:tVDNdYkHrtokDcQQgYSbSg==
    - tmrdh.symfony-helper@1.0.7:M/uifzidipfdLveowCveCQ==
    - mblode.twig-language-2@0.9.0:mWsNqa1LweaaXTuVKMzPvg==