# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        # this internal class is used by Symfony to represent in-memory users
        Symfony\Component\Security\Core\User\User: 'plaintext'
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        backend_users:
            memory:
                users:
                    ndongala.augusto@nova-erp.com: { password: '$2y$13$jxGxcIuqDju', roles: ['ROLE_ADMIN'] }
                    sebastiao.lutonda@nova-erp.com: { password: '$2y$13$PFi1IrGwXCZ', roles: ['ROLE_ADMIN', 'ROLE_SUPER_ADMIN'] }
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|stylesheet.css|images|js)/
            security: false

        main:

            # ...
            http_basic:
                realm: Secured Area
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
